import streamlit as st
from dataset_loader import render_upload
from visualization import plot_dashboard
from llm_utils import get_ai_explanation
from analysis_pipeline import run_analysis
from ui import (render_sidebar, render_dataset_overview, 
                render_configuration, render_ai_summary, render_downloads)
from report_generator import (build_full_report, generate_pdf_report)

st.set_page_config(
    page_title="AI Bias Detection System",
    page_icon="⚖️",
    layout="wide",
    initial_sidebar_state="expanded"
)

st.title("⚖️ AI Bias Detection System")

st.markdown("""
Detect, analyze and mitigate bias in machine learning datasets using
AIF360, Reweighing and Local LLM-powered fairness explanations.
""")

st.divider()

render_sidebar()

defaults = {

    "df": None,
    "analysis": None,

}

for key, value in defaults.items():
    st.session_state.setdefault(key, value)

df = render_upload()

if df is not None:
    render_dataset_overview(df)

    target_col, protected_col, analyze = render_configuration(df)

    if analyze:

        try:

            analysis = run_analysis(
                df,
                target_col,
                protected_col
            )

            if analysis is None:
                st.stop()

            st.session_state.analysis = analysis

            plot_dashboard(analysis)

            with st.spinner("Generating AI explanation..."):

                try:
                    llm_response = get_ai_explanation(analysis)

                except Exception:
                    import traceback

                    traceback.print_exc()

                    raise
            #         llm_response = """
            # ## Interpretation

            # AI explanation could not be generated because the local Ollama server is unavailable.

            # ## Recommendations

            # - Start the Ollama server.
            # - Verify the configured model is installed.
            # - Rerun the analysis.

            # ## Limitations

            # This report contains only the deterministic analysis generated by the application.
            # """

            ai_summary = build_full_report(
                analysis,
                llm_response
            )

            pdf_report = generate_pdf_report(ai_summary)

            render_ai_summary(ai_summary)
            
            render_downloads(analysis, ai_summary, pdf_report)

            st.session_state.ai_summary = ai_summary

        except Exception as e:

            st.error("Analysis failed.")
            st.exception(e)