import streamlit as st
from CORE.dataset_loader import render_upload
from UI.visualization import plot_dashboard
from CORE.llm_utils import get_ai_explanation
from CORE.analysis_pipeline import run_analysis
from UI.ui import (render_dataset_overview, render_verdict,
                render_configuration, render_ai_summary, render_downloads)
from CORE.report_generator import (build_full_report, generate_pdf_report)
from UI.theme import load_css
from app_state import (initialize_state, update_status)
from UI.sidebar import render_sidebar

st.set_page_config(
    page_title="AI Bias Detection System",
    page_icon="⚖️",
    layout="wide",
    initial_sidebar_state="expanded"
)

load_css()

st.title("⚖️ AI Bias Detection System")

st.markdown("""
Detect, analyze and mitigate bias in machine learning datasets using
AIF360, Reweighing and Local LLM-powered fairness explanations.
""")

st.divider()

initialize_state()

defaults = {

    "df": None,
    "analysis": None,

}

for key, value in defaults.items():
    st.session_state.setdefault(key, value)

df = render_upload()

if df is not None:
    update_status("dataset_loaded") 
    render_dataset_overview(df)

    target_col, protected_col, analyze = render_configuration(df)

    if analyze:
        update_status("dataset_configured")

        try:

            analysis = run_analysis(
                df,
                target_col,
                protected_col
            )

            if analysis is None:
                st.stop()

            update_status("fairness_analysis_completed")

            st.session_state.analysis = analysis

            plot_dashboard(analysis)

            with st.spinner("Generating AI explanation..."):

                try:
                    llm_response = get_ai_explanation(analysis)

                except Exception:
                    import traceback

                    traceback.print_exc()

                    raise
            #         llm_response = """
            # ## Interpretation

            # AI explanation could not be generated because the local Ollama server is unavailable.

            # ## Recommendations

            # - Start the Ollama server.
            # - Verify the configured model is installed.
            # - Rerun the analysis.

            # ## Limitations

            # This report contains only the deterministic analysis generated by the application.
            # """

            render_verdict(analysis)

            ai_summary = build_full_report(
                analysis,
                llm_response
            )

            update_status("ai_report_generated")

            pdf_report = generate_pdf_report(ai_summary)

            render_ai_summary(ai_summary)
            
            render_downloads(analysis, ai_summary, pdf_report)

            st.session_state.ai_summary = ai_summary

            update_status("export_ready")

        except Exception as e:

            st.error("Analysis failed.")
            st.exception(e)

render_sidebar()